version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: kubdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

  django:
    build: ./kubBackend
    container_name: django_container
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=kubdb
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD="1"
    ports:
      - "8000:8000"

  frontend:
    build: ./my-app
    container_name: react_app
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://django:8000
    depends_on:
      - django
volumes:
  postgres_data: