FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client && rm -rf /var/lib/apt/lists/*
COPY kubBackend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt && apt-get update && apt-get install -y postgresql-client


COPY kubBackend /app/

# COPY /kubBackend/dockerfiles/dockerfile_for_sockets/entrypoint.sh /entrypoint.sh
RUN chmod +x ./dockerfiles/dockerfile_for_sockets/entrypoint.sh && sed -i 's/\r$//' ./dockerfiles/dockerfile_for_sockets/entrypoint.sh

CMD ["/app/dockerfiles/dockerfile_for_sockets/entrypoint.sh"]
