FROM python:3.12-slim

WORKDIR /app

COPY ./kubBackend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y postgresql-client


COPY . /app/

COPY ./kubBackend/dockerfiles/dockerfile_for_rest/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["./entrypoint.sh"]
